### ISSUE TITLE
Error when trying to run the installer 

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud_installer#92]
This problem is related to js9 image
```
root@management-667649f744-rw6z8:/# installer --config config.yaml cluster updatedomain
Writing certificates
Write system config
Waiting for nginx to be ready..
Waiting for portal to be ready..
Installing teleport be-g8-3-ctrl-01.be-g8-3
Traceback (most recent call last):
  File "/opt/code/github/0-complexity/openvcloud_installer/scripts/install/installer", line 1182, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/code/github/0-complexity/openvcloud_installer/scripts/install/installer", line 1169, in cluster_updatedomain
    cluster.install_teleport()
  File "/opt/code/github/0-complexity/openvcloud_installer/scripts/install/installer", line 839, in install_teleport
    node.apps.teleport.restart()
  File "/opt/code/github/jumpscale/prefab9/modules/apps/PrefabTeleport.py", line 212, in restart
    self.start()
  File "/opt/code/github/jumpscale/prefab9/modules/apps/PrefabTeleport.py", line 197, in start
    pm.ensure(name='teleport', cmd=cmd)
  File "/opt/code/github/jumpscale/prefab9/modules/system/ProcessManager.py", line 112, in ensure
    cmd = self.prefab.core._clean(cmd)
AttributeError: 'PrefabCore' object has no attribute '_clean'
'PrefabCore' object has no attribute '_clean'
```

**Comment by alichaddad** [comment]
js9 image was updated
